# Generated by Django 5.0.4 on 2026-06-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField(unique=True)),
                ('season', models.IntegerField()),
                ('city', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('toss_winner', models.CharField(max_length=100)),
                ('toss_decision', models.CharField(max_length=20)),
                ('winner', models.CharField(blank=True, max_length=100)),
                ('win_by_runs', models.IntegerField(default=0)),
                ('win_by_wickets', models.IntegerField(default=0)),
                ('venue', models.CharField(max_length=200)),
                ('player_of_match', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=100)),
                ('season', models.IntegerField()),
                ('balls', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('against', models.CharField(blank=True, max_length=100)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('record_type', models.CharField(choices=[('century', 'Century'), ('fifty', 'Fifty')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BattingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(db_index=True, max_length=100)),
                ('season', models.IntegerField(db_index=True)),
                ('matches', models.IntegerField(default=0)),
                ('innings', models.IntegerField(default=0)),
                ('runs', models.IntegerField(default=0)),
                ('balls_faced', models.IntegerField(default=0)),
                ('highest_score', models.CharField(blank=True, max_length=10)),
                ('average', models.FloatField(default=0.0)),
                ('strike_rate', models.FloatField(default=0.0)),
                ('hundreds', models.IntegerField(default=0)),
                ('fifties', models.IntegerField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('dot_balls', models.IntegerField(default=0)),
                ('not_outs', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('player', 'season')},
            },
        ),
        migrations.CreateModel(
            name='BowlingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(db_index=True, max_length=100)),
                ('season', models.IntegerField(db_index=True)),
                ('matches', models.IntegerField(default=0)),
                ('innings', models.IntegerField(default=0)),
                ('overs', models.FloatField(default=0.0)),
                ('runs_conceded', models.IntegerField(default=0)),
                ('wickets', models.IntegerField(default=0)),
                ('economy', models.FloatField(default=0.0)),
                ('strike_rate', models.FloatField(default=0.0)),
                ('best_bowling', models.CharField(blank=True, max_length=10)),
                ('four_wickets', models.IntegerField(default=0)),
                ('five_wickets', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('player', 'season')},
            },
        ),
    ]
