# Generated by Django 5.0.4 on 2026-07-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='video_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
